use aios_core::pdms_types::RefU64;
use anyhow::Result;
use nalgebra::{Point3, Vector3};
use std::fs::File;
use std::io::Write;
use std::path::Path;

use crate::grpc_service::sctn_collision_optimizer::CollisionPair;
use crate::grpc_service::sctn_contact_detector::{
    CableTraySection, ContactResult, ContactType, SupportRelation,
};
use crate::grpc_service::sctn_path_analyzer::TrayPath;

/// SCTN可视化调试工具
pub struct SctnVisualizer {
    output_dir: String,
}

impl SctnVisualizer {
    pub fn new(output_dir: impl Into<String>) -> Self {
        Self {
            output_dir: output_dir.into(),
        }
    }

    /// 导出为OBJ格式（可在3D软件中查看）
    pub fn export_to_obj(&self, sections: &[CableTraySection], filename: &str) -> Result<()> {
        let path = Path::new(&self.output_dir).join(filename);
        let mut file = File::create(path)?;

        writeln!(file, "# SCTN Cable Tray Sections")?;
        writeln!(file, "# Generated by SCTN Visualizer")?;
        writeln!(file, "")?;

        let mut vertex_offset = 1;

        for (i, section) in sections.iter().enumerate() {
            writeln!(file, "# Section {} (RefNo: {})", i, section.refno.0)?;
            writeln!(file, "g section_{}", section.refno.0)?;

            // 生成立方体顶点
            let vertices = self.generate_box_vertices(&section.bbox);

            // 写入顶点
            for v in &vertices {
                writeln!(file, "v {} {} {}", v.x, v.y, v.z)?;
            }

            // 写入面（立方体有6个面）
            let faces = [
                [1, 2, 4, 3], // 底面
                [5, 6, 8, 7], // 顶面
                [1, 2, 6, 5], // 前面
                [3, 4, 8, 7], // 后面
                [1, 3, 7, 5], // 左面
                [2, 4, 8, 6], // 右面
            ];

            for face in &faces {
                write!(file, "f")?;
                for &idx in face {
                    write!(file, " {}", idx + vertex_offset - 1)?;
                }
                writeln!(file)?;
            }

            vertex_offset += 8;
            writeln!(file)?;
        }

        Ok(())
    }

    /// 导出为HTML可视化（使用Three.js）
    pub fn export_to_html(
        &self,
        sections: &[CableTraySection],
        contacts: &[(RefU64, ContactResult)],
        supports: &[SupportRelation],
        filename: &str,
    ) -> Result<()> {
        let path = Path::new(&self.output_dir).join(filename);
        let mut file = File::create(path)?;

        writeln!(file, "<!DOCTYPE html>")?;
        writeln!(file, "<html>")?;
        writeln!(file, "<head>")?;
        writeln!(file, "    <title>SCTN Visualization</title>")?;
        writeln!(file, "    <style>")?;
        writeln!(file, "        body {{ margin: 0; overflow: hidden; }}")?;
        writeln!(file, "        #info {{")?;
        writeln!(file, "            position: absolute;")?;
        writeln!(file, "            top: 10px;")?;
        writeln!(file, "            left: 10px;")?;
        writeln!(file, "            color: white;")?;
        writeln!(file, "            background: rgba(0,0,0,0.7);")?;
        writeln!(file, "            padding: 10px;")?;
        writeln!(file, "            border-radius: 5px;")?;
        writeln!(file, "        }}")?;
        writeln!(file, "    </style>")?;
        writeln!(file, "</head>")?;
        writeln!(file, "<body>")?;

        writeln!(file, "<div id='info'>")?;
        writeln!(file, "    <h3>SCTN Visualization</h3>")?;
        writeln!(file, "    <p>Sections: {}</p>", sections.len())?;
        writeln!(file, "    <p>Contacts: {}</p>", contacts.len())?;
        writeln!(file, "    <p>Supports: {}</p>", supports.len())?;
        writeln!(file, "    <p>Controls: Mouse to rotate, Scroll to zoom</p>")?;
        writeln!(file, "</div>")?;

        writeln!(
            file,
            "<script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js'></script>"
        )?;
        writeln!(file, "<script>")?;

        // Three.js场景设置
        writeln!(file, "const scene = new THREE.Scene();")?;
        writeln!(file, "scene.background = new THREE.Color(0x222222);")?;
        writeln!(file, "")?;

        writeln!(
            file,
            "const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);"
        )?;
        writeln!(file, "camera.position.set(10, 10, 10);")?;
        writeln!(file, "camera.lookAt(0, 0, 0);")?;
        writeln!(file, "")?;

        writeln!(file, "const renderer = new THREE.WebGLRenderer();")?;
        writeln!(
            file,
            "renderer.setSize(window.innerWidth, window.innerHeight);"
        )?;
        writeln!(file, "document.body.appendChild(renderer.domElement);")?;
        writeln!(file, "")?;

        // 添加光源
        writeln!(
            file,
            "const ambientLight = new THREE.AmbientLight(0x404040);"
        )?;
        writeln!(file, "scene.add(ambientLight);")?;
        writeln!(file, "")?;

        writeln!(
            file,
            "const directionalLight = new THREE.DirectionalLight(0xffffff, 1);"
        )?;
        writeln!(file, "directionalLight.position.set(5, 10, 5);")?;
        writeln!(file, "scene.add(directionalLight);")?;
        writeln!(file, "")?;

        // 添加网格
        writeln!(file, "const gridHelper = new THREE.GridHelper(20, 20);")?;
        writeln!(file, "scene.add(gridHelper);")?;
        writeln!(file, "")?;

        // 添加SCTN几何体
        writeln!(file, "// SCTN Sections")?;
        for section in sections {
            let color = self.get_section_color(section, contacts);
            self.write_box_geometry(&mut file, section, color)?;
        }

        // 添加接触点可视化
        writeln!(file, "// Contact Points")?;
        for (_, contact) in contacts {
            for point in &contact.contact_points {
                self.write_sphere_geometry(&mut file, point, 0xff0000, 0.05)?;
            }
        }

        // 添加支撑点可视化
        writeln!(file, "// Support Points")?;
        for support in supports {
            self.write_sphere_geometry(&mut file, &support.contact_point, 0x00ff00, 0.08)?;
        }

        // 添加鼠标控制
        writeln!(file, "// Mouse Controls")?;
        writeln!(file, "let mouseX = 0, mouseY = 0;")?;
        writeln!(file, "document.addEventListener('mousemove', (event) => {{")?;
        writeln!(
            file,
            "    mouseX = (event.clientX / window.innerWidth) * 2 - 1;"
        )?;
        writeln!(
            file,
            "    mouseY = -(event.clientY / window.innerHeight) * 2 + 1;"
        )?;
        writeln!(file, "}});")?;
        writeln!(file, "")?;

        // 动画循环
        writeln!(file, "function animate() {{")?;
        writeln!(file, "    requestAnimationFrame(animate);")?;
        writeln!(
            file,
            "    camera.position.x += (mouseX * 20 - camera.position.x) * 0.05;"
        )?;
        writeln!(
            file,
            "    camera.position.y += (mouseY * 20 - camera.position.y) * 0.05;"
        )?;
        writeln!(file, "    camera.lookAt(scene.position);")?;
        writeln!(file, "    renderer.render(scene, camera);")?;
        writeln!(file, "}}")?;
        writeln!(file, "animate();")?;

        writeln!(file, "</script>")?;
        writeln!(file, "</body>")?;
        writeln!(file, "</html>")?;

        Ok(())
    }

    /// 导出为CSV格式（用于数据分析）
    pub fn export_to_csv(
        &self,
        sections: &[CableTraySection],
        contacts: &[(RefU64, ContactResult)],
        filename: &str,
    ) -> Result<()> {
        let path = Path::new(&self.output_dir).join(filename);
        let mut file = File::create(path)?;

        // 写入头部
        writeln!(
            file,
            "RefNo,Type,Width,Height,Depth,CenterX,CenterY,CenterZ,DirectionX,DirectionY,DirectionZ,ContactCount"
        )?;

        // 统计每个SCTN的接触数
        let mut contact_counts = std::collections::HashMap::new();
        for (refno, _) in contacts {
            *contact_counts.entry(*refno).or_insert(0) += 1;
        }

        // 写入数据
        for section in sections {
            let center = section.bbox.center();
            let contact_count = contact_counts.get(&section.refno).unwrap_or(&0);

            writeln!(
                file,
                "{},{},{},{},{},{},{},{},{},{},{},{}",
                section.refno.0,
                section.section_type,
                section.width,
                section.height,
                section.depth,
                center.x,
                center.y,
                center.z,
                section.direction.x,
                section.direction.y,
                section.direction.z,
                contact_count
            )?;
        }

        Ok(())
    }

    /// 导出碰撞报告
    pub fn export_collision_report(
        &self,
        collisions: &[CollisionPair],
        filename: &str,
    ) -> Result<()> {
        let path = Path::new(&self.output_dir).join(filename);
        let mut file = File::create(path)?;

        writeln!(file, "# SCTN Collision Report")?;
        writeln!(file, "# Total Collisions: {}", collisions.len())?;
        writeln!(file, "")?;

        // 按类型分组
        let mut by_type = std::collections::HashMap::new();
        for collision in collisions {
            by_type
                .entry(format!("{:?}", collision.contact_type))
                .or_insert_with(Vec::new)
                .push(collision);
        }

        for (contact_type, group) in by_type {
            writeln!(file, "## {} ({})", contact_type, group.len())?;
            writeln!(file, "")?;

            for collision in group {
                writeln!(
                    file,
                    "- SCTN {} <-> SCTN {}: Penetration: {:.3}mm",
                    collision.section1.0,
                    collision.section2.0,
                    collision.penetration_depth * 1000.0
                )?;

                if !collision.contact_points.is_empty() {
                    writeln!(
                        file,
                        "  Contact at: ({:.2}, {:.2}, {:.2})",
                        collision.contact_points[0].x,
                        collision.contact_points[0].y,
                        collision.contact_points[0].z
                    )?;
                }
            }
            writeln!(file, "")?;
        }

        Ok(())
    }

    /// 导出路径可视化
    pub fn export_path_visualization(
        &self,
        path: &TrayPath,
        sections: &[CableTraySection],
        filename: &str,
    ) -> Result<()> {
        let path_file = Path::new(&self.output_dir).join(filename);
        let mut file = File::create(path_file)?;

        writeln!(file, "# SCTN Path Visualization")?;
        writeln!(file, "# From: {} To: {}", path.from.0, path.to.0)?;
        writeln!(file, "# Total Length: {:.2}m", path.total_length)?;
        writeln!(file, "# Sections in path: {}", path.sections.len())?;
        writeln!(file, "")?;

        // 创建查找表
        let section_map: std::collections::HashMap<RefU64, &CableTraySection> =
            sections.iter().map(|s| (s.refno, s)).collect();

        writeln!(file, "Path sequence:")?;
        for (i, refno) in path.sections.iter().enumerate() {
            if let Some(section) = section_map.get(refno) {
                let center = section.bbox.center();
                writeln!(
                    file,
                    "{}: SCTN {} at ({:.2}, {:.2}, {:.2})",
                    i + 1,
                    refno.0,
                    center.x,
                    center.y,
                    center.z
                )?;
            }
        }

        Ok(())
    }

    // 辅助函数

    fn generate_box_vertices(&self, bbox: &parry3d::bounding_volume::Aabb) -> Vec<Point3<f32>> {
        vec![
            Point3::new(bbox.mins.x, bbox.mins.y, bbox.mins.z),
            Point3::new(bbox.maxs.x, bbox.mins.y, bbox.mins.z),
            Point3::new(bbox.mins.x, bbox.maxs.y, bbox.mins.z),
            Point3::new(bbox.maxs.x, bbox.maxs.y, bbox.mins.z),
            Point3::new(bbox.mins.x, bbox.mins.y, bbox.maxs.z),
            Point3::new(bbox.maxs.x, bbox.mins.y, bbox.maxs.z),
            Point3::new(bbox.mins.x, bbox.maxs.y, bbox.maxs.z),
            Point3::new(bbox.maxs.x, bbox.maxs.y, bbox.maxs.z),
        ]
    }

    fn get_section_color(
        &self,
        section: &CableTraySection,
        contacts: &[(RefU64, ContactResult)],
    ) -> u32 {
        for (refno, contact) in contacts {
            if *refno == section.refno {
                return match contact.contact_type {
                    ContactType::Penetration => 0xff0000, // 红色
                    ContactType::Surface => 0xffff00,     // 黄色
                    ContactType::Proximity => 0x00ffff,   // 青色
                    _ => 0x808080,                        // 灰色
                };
            }
        }
        0x808080 // 默认灰色
    }

    fn write_box_geometry(
        &self,
        file: &mut File,
        section: &CableTraySection,
        color: u32,
    ) -> Result<()> {
        let center = section.bbox.center();
        let size = section.bbox.maxs - section.bbox.mins;

        writeln!(file, "{{")?;
        writeln!(
            file,
            "    const geometry = new THREE.BoxGeometry({}, {}, {});",
            size.x, size.y, size.z
        )?;
        writeln!(
            file,
            "    const material = new THREE.MeshPhongMaterial({{color: 0x{:06x}, opacity: 0.7, transparent: true}});",
            color
        )?;
        writeln!(file, "    const mesh = new THREE.Mesh(geometry, material);")?;
        writeln!(
            file,
            "    mesh.position.set({}, {}, {});",
            center.x, center.y, center.z
        )?;
        writeln!(file, "    scene.add(mesh);")?;
        writeln!(file, "}}")?;

        Ok(())
    }

    fn write_sphere_geometry(
        &self,
        file: &mut File,
        position: &Point3<f32>,
        color: u32,
        radius: f32,
    ) -> Result<()> {
        writeln!(file, "{{")?;
        writeln!(
            file,
            "    const geometry = new THREE.SphereGeometry({}, 8, 8);",
            radius
        )?;
        writeln!(
            file,
            "    const material = new THREE.MeshBasicMaterial({{color: 0x{:06x}}});",
            color
        )?;
        writeln!(
            file,
            "    const sphere = new THREE.Mesh(geometry, material);"
        )?;
        writeln!(
            file,
            "    sphere.position.set({}, {}, {});",
            position.x, position.y, position.z
        )?;
        writeln!(file, "    scene.add(sphere);")?;
        writeln!(file, "}}")?;

        Ok(())
    }
}
