SELECT meta::id(id) AS id, noun, name, cata_hash, type::string(refno.SPRE) AS spre, refno.SPRE.name AS spre_name, refno.DESP AS desp FROM pe:`24381_145032`;
SELECT meta::id(id) AS id, noun, name, cata_hash, type::string(refno.SPRE) AS spre, refno.SPRE.name AS spre_name, refno.DESP AS desp FROM pe:`24381_145035`;
SELECT meta::id(id) AS id, noun, name, cata_hash, type::string(refno.SPRE) AS spre, refno.SPRE.name AS spre_name, refno.DESP AS desp FROM pe:`24381_145019`;
SELECT meta::id(id) AS id, noun, name FROM pe:`13246_368855`;
SELECT meta::id(id) AS id, noun, name, owner FROM pe WHERE owner = pe:`13246_371151`;
