import type { RouteRecordRaw } from 'vue-router';

import DashboardView from '@/views/DashboardView.vue';
import AdminRedirectView from '@/views/AdminRedirectView.vue';
import CollaborationRedirectView from '@/views/CollaborationRedirectView.vue';
import PlaceholderView from '@/views/PlaceholderView.vue';
import ProjectDetailPlaceholderView from '@/views/ProjectDetailPlaceholderView.vue';
import ProjectsView from '@/views/ProjectsView.vue';
import TasksView from '@/views/TasksView.vue';

export const appRoutes: RouteRecordRaw[] = [
  {
    path: '/',
    redirect: '/dashboard',
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    component: DashboardView,
    meta: {
      title: 'Dashboard',
      navGroup: 'Dashboard',
      navLabel: 'Overview',
      navIcon: 'dashboard',
      navOrder: 10,
    },
  },
  {
    path: '/projects',
    name: 'projects',
    component: ProjectsView,
    meta: {
      title: 'Projects',
      navGroup: 'Projects',
      navLabel: 'Project Hub',
      navIcon: 'projects',
      navOrder: 20,
    },
  },
  {
    path: '/projects/:projectId',
    name: 'project-detail',
    component: ProjectDetailPlaceholderView,
    meta: {
      title: 'Project Workspace',
    },
  },
  {
    path: '/tasks',
    name: 'tasks',
    component: TasksView,
    meta: {
      title: 'Tasks',
      navGroup: 'Tasks',
      navLabel: 'Task Center',
      navIcon: 'tasks',
      navOrder: 30,
    },
  },
  {
    path: '/tasks/batch',
    name: 'tasks-batch',
    component: PlaceholderView,
    props: {
      eyebrow: 'Tasks',
      title: 'Batch tasks placeholder',
      description: 'Batch task orchestration is reserved under the unified console route and will replace the legacy batch page in a follow-up milestone.',
      chips: ['Deep-link ready', 'Legacy mapping target'],
    },
    meta: {
      title: 'Batch Tasks',
      navGroup: 'Tasks',
      navLabel: 'Batch Tasks',
      navIcon: 'batch',
      navOrder: 31,
    },
  },
  {
    path: '/deployment/sites',
    name: 'deployment-sites',
    component: AdminRedirectView,
    props: {
      eyebrow: 'Deployment',
      title: 'Deployment sites redirect',
      description: 'Deployment site management has moved to `/admin#/registry`, and this route now only preserves old deep links.',
      chips: ['Admin', 'Redirect'],
    },
    meta: {
      title: 'Deployment Sites',
      navGroup: 'Deployment',
      navLabel: 'Sites',
      navIcon: 'deployment',
      navOrder: 40,
      navHidden: true,
    },
  },
  {
    path: '/deployment/wizard',
    name: 'deployment-wizard',
    component: PlaceholderView,
    props: {
      eyebrow: 'Deployment',
      title: 'Wizard placeholder',
      description: 'The deployment wizard will move here so legacy `/wizard` can redirect into the SPA without falling back to server-rendered HTML.',
      chips: ['Scan directory', 'Create task'],
    },
    meta: {
      title: 'Deployment Wizard',
      navGroup: 'Deployment',
      navLabel: 'Wizard',
      navIcon: 'wizard',
      navOrder: 41,
    },
  },
  {
    path: '/sync/control',
    name: 'sync-control',
    component: PlaceholderView,
    props: {
      eyebrow: 'Sync',
      title: 'Sync control placeholder',
      description: 'This placeholder reserves the control center route for SSE, queue, and runtime actions while keeping the navigation under `/console/*`.',
      chips: ['Control', 'Events', 'Queue'],
    },
    meta: {
      title: 'Sync Control',
      navGroup: 'Sync',
      navLabel: 'Control',
      navIcon: 'sync',
      navOrder: 50,
    },
  },
  {
    path: '/sync/remote',
    name: 'sync-remote',
    component: CollaborationRedirectView,
    props: {
      eyebrow: 'Sync',
      title: 'Remote sync redirect',
      description: 'Remote sync management has moved to `/admin/#/collaboration`, and this route now only preserves old deep links.',
      chips: ['Admin', 'Redirect', 'Collaboration'],
    },
    meta: {
      title: 'Remote Sync',
      navGroup: 'Sync',
      navLabel: 'Remote Sync',
      navIcon: 'remote',
      navOrder: 51,
      navHidden: true,
    },
  },
  {
    path: '/sync/incremental',
    name: 'sync-incremental',
    component: PlaceholderView,
    props: {
      eyebrow: 'Sync',
      title: 'Incremental sync placeholder',
      description: 'Incremental detect and sync flows can now refresh directly under the console base path without 404s.',
      chips: ['Detect', 'Task status', 'Cancel'],
    },
    meta: {
      title: 'Incremental Sync',
      navGroup: 'Sync',
      navLabel: 'Incremental',
      navIcon: 'incremental',
      navOrder: 52,
    },
  },
  {
    path: '/db/status',
    name: 'db-status',
    component: PlaceholderView,
    props: {
      eyebrow: 'DB',
      title: 'Database status placeholder',
      description: 'Database status now has a stable SPA route for refresh and navigation checks while the full data surface is migrated.',
      chips: ['Status', 'Versions', 'Actions'],
    },
    meta: {
      title: 'DB Status',
      navGroup: 'DB',
      navLabel: 'Status',
      navIcon: 'db',
      navOrder: 60,
    },
  },
  {
    path: '/db/sqlite-spatial',
    name: 'db-sqlite-spatial',
    component: PlaceholderView,
    props: {
      eyebrow: 'DB',
      title: 'SQLite spatial placeholder',
      description: 'Spatial query and index tooling will converge on this route, giving legacy spatial pages a canonical SPA destination.',
      chips: ['Spatial query', 'Index stats'],
    },
    meta: {
      title: 'SQLite Spatial',
      navGroup: 'DB',
      navLabel: 'SQLite Spatial',
      navIcon: 'spatial',
      navOrder: 61,
    },
  },
  {
    path: '/db/spatial-visualization',
    name: 'db-spatial-visualization',
    component: PlaceholderView,
    props: {
      eyebrow: 'DB',
      title: 'Spatial visualization placeholder',
      description: 'Visualization tooling is intentionally deferred, but the placeholder route proves the `/console` history fallback and nav wiring.',
      chips: ['Visualization', 'Deferred'],
    },
    meta: {
      title: 'Spatial Visualization',
      navGroup: 'DB',
      navLabel: 'Visualization',
      navIcon: 'visualization',
      navOrder: 62,
    },
  },
  {
    path: '/settings/config',
    name: 'settings-config',
    component: PlaceholderView,
    props: {
      eyebrow: 'Settings',
      title: 'Config placeholder',
      description: 'Configuration management gets a dedicated SPA destination now, with UI migration following in the next milestone.',
      chips: ['Config', 'Templates'],
    },
    meta: {
      title: 'Config',
      navGroup: 'Settings',
      navLabel: 'Config',
      navIcon: 'settings',
      navOrder: 70,
    },
  },
  {
    path: '/settings/database-connection',
    name: 'settings-database-connection',
    component: PlaceholderView,
    props: {
      eyebrow: 'Settings',
      title: 'Database connection placeholder',
      description: 'Diagnostics and connectivity checks will move here while keeping the shell consistent and deep-link safe.',
      chips: ['Diagnostics', 'Connectivity'],
    },
    meta: {
      title: 'Database Connection',
      navGroup: 'Settings',
      navLabel: 'Database Connection',
      navIcon: 'connection',
      navOrder: 71,
    },
  },
  {
    path: '/tools/space-tools',
    name: 'tools-space-tools',
    component: PlaceholderView,
    props: {
      eyebrow: 'Tools',
      title: 'Space tools placeholder',
      description: 'Space calculation tools will move under the dashboard shell without breaking direct links or group-based navigation.',
      chips: ['Space tools', 'Deferred'],
    },
    meta: {
      title: 'Space Tools',
      navGroup: 'Tools',
      navLabel: 'Space Tools',
      navIcon: 'tools',
      navOrder: 80,
    },
  },
  {
    path: '/tools/tray-supports',
    name: 'tools-tray-supports',
    component: PlaceholderView,
    props: {
      eyebrow: 'Tools',
      title: 'Tray supports placeholder',
      description: 'Tray support detection remains available as a planned console destination ready for validation and follow-up implementation.',
      chips: ['Tray supports', 'Detection'],
    },
    meta: {
      title: 'Tray Supports',
      navGroup: 'Tools',
      navLabel: 'Tray Supports',
      navIcon: 'tray',
      navOrder: 81,
    },
  },
  {
    path: '/tools/sctn-test',
    name: 'tools-sctn-test',
    component: PlaceholderView,
    props: {
      eyebrow: 'Tools',
      title: 'SCTN test placeholder',
      description: 'SCTN test execution will land here later; for now this route validates navigation grouping and history refresh behavior.',
      chips: ['SCTN', 'Run + poll'],
    },
    meta: {
      title: 'SCTN Test',
      navGroup: 'Tools',
      navLabel: 'SCTN Test',
      navIcon: 'sctn',
      navOrder: 82,
    },
  },
  {
    path: '/tools/room-management',
    name: 'tools-room-management',
    component: PlaceholderView,
    props: {
      eyebrow: 'Tools',
      title: 'Room management placeholder',
      description: 'Room management keeps a dedicated SPA endpoint now so the shell and redirects can be validated before the page is migrated.',
      chips: ['Room management', 'Deferred'],
    },
    meta: {
      title: 'Room Management',
      navGroup: 'Tools',
      navLabel: 'Room Management',
      navIcon: 'room',
      navOrder: 83,
    },
  },
  {
    path: '/viewer/preview',
    name: 'viewer-preview',
    component: PlaceholderView,
    props: {
      eyebrow: 'Viewer',
      title: 'Viewer preview is not implemented yet',
      description: 'This console keeps a visible preview entry so the upcoming viewer work can hook into the dashboard shell without changing route contracts.',
      chips: ['Preview', 'Reserved entry'],
    },
    meta: {
      title: 'Viewer Preview',
      navGroup: 'Viewer',
      navLabel: 'Preview',
      navIcon: 'viewer',
      navOrder: 90,
    },
  },
];
